### ISSUE TITLE
Agregarse a un canal

### ISSUE THREAD

**Issue by gascoj** [ProyectoFinalCAECE/comet-client#17]
No funciona la opción de agregarse a un canal

**Comment by marianoquevedo** [comment]
Estuve probando y al parecer el problema es cuando te borras del canal y despúes querés volver a agregarte. 
Parece ser un problema de backend ( lo mas probable es que tenga que ver con el borrado lógico)

**Comment by jsaucedo** [comment]
estoy laburando en esto ahora

**Comment by jsaucedo** [comment]
ya funciona server side
