### ISSUE TITLE
Cambiar Icono para agregar usuarios

### ISSUE THREAD

**Issue by gascoj** [ProyectoFinalCAECE/comet-client#18]
cambiar icono de agregar usuarios en el canal y re definir los iconos

**Comment by marianoquevedo** [comment]
Ojo con esto muchachos que yo estuve tocando en el explorar canal. 
El icono del "+" (u otro similar) lo seguimos necesitando para que el usuario se agregue al canal.
Aparte tenemos el icono del grupito que muestra la sidebar con los usuarios y ahí dentro el link con "+ agregar participantes"

<img width="998" alt="screenshot 2015-10-20 01 46 36" src="https://cloud.githubusercontent.com/assets/12384762/10598129/83e33728-76cc-11e5-81e4-608901e86669.png">

<img width="1033" alt="screenshot 2015-10-20 01 48 04" src="https://cloud.githubusercontent.com/assets/12384762/10598144/ad9eadd6-76cc-11e5-84b7-0ce9bb2beb96.png">

**Comment by gascoj** [comment]
Ahora abajo quedo agregar participar en vez de participante

![ev_comet1](https://cloud.githubusercontent.com/assets/13737487/10637732/909d248a-77dd-11e5-8e45-24b46a55ef5f.jpg)

**Comment by AlanRossi92** [comment]
Quedo corregido el "Agregar participar" por "Agregar participante"
