### ISSUE TITLE
Menu desplegable para administrar 

### ISSUE THREAD

**Issue by gascoj** [ProyectoFinalCAECE/comet-client#20]
El menu desplegable para cerrar/eliminar o salir de un canal queda afuera de la pantalla al seleccionarlo ahora y no tengo manera de verlo completo

![ev2_comet](https://cloud.githubusercontent.com/assets/13737487/10638067/69d8ff52-77df-11e5-8428-808c391b12ec.jpg)

**Comment by mvilloria** [comment]
Se movio la posicion para que quede adentro del display.
